apiVersion: apps/v1
kind: Deployment
metadata:
  name: devloop-kustomize
  labels:
    app: devloop-kustomize
spec:
  selector:
    matchLabels:
      app: devloop-kustomize
  template:
    metadata:
      labels:
        app: devloop-kustomize
    spec:
      containers:
      - name: devloop-kustomize
        image: devloop-kustomize
